name: Hello World

on:
  # Enables manual trigger
  workflow_dispatch: 
  # When code is pushed to the repo
  push:
  # When code is pulled from the repo
  pull_request:
jobs:
  say-hello:
    runs-on: ubuntu-latest # Uses the latest ubuntu runner
    steps:
      - name: prints out Hello World
        run: echo "Hello World"    
